### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by imirrori** [SnigurSA/LevelUp_stage1#1]
https://github.com/SnigurSA/LevelUp_stage1/blob/b2a8e44e0bb02e8eb23fd941f62873c60fbbb836/dz4/dz4-1/dz4-1.cpp#L12
Лишний пробел

https://github.com/SnigurSA/LevelUp_stage1/blob/b2a8e44e0bb02e8eb23fd941f62873c60fbbb836/dz4/dz4-1/dz4-1.cpp#L15
<= не правильное условие

https://github.com/SnigurSA/LevelUp_stage1/blob/b2a8e44e0bb02e8eb23fd941f62873c60fbbb836/dz4/dz4-1/dz4-1.cpp#L22
<= не правильное условие
сдвиг тела цикла не правильный

https://github.com/SnigurSA/LevelUp_stage1/blob/b2a8e44e0bb02e8eb23fd941f62873c60fbbb836/dz4/dz4-1/dz4-1.cpp#L27
Не надо разделять объевление и нициализацию.
int maxi = 0;

https://github.com/SnigurSA/LevelUp_stage1/blob/b2a8e44e0bb02e8eb23fd941f62873c60fbbb836/dz4/dz4-1/dz4-1.cpp#L50
Сдвиг не тот

https://github.com/SnigurSA/LevelUp_stage1/blob/b2a8e44e0bb02e8eb23fd941f62873c60fbbb836/dz4/dz4-2/dz4-2.cpp#L19
Пробельчика после % не хватает

В этом фале сдвиги и <= условия не правльные в циклах.

https://github.com/SnigurSA/LevelUp_stage1/blob/b2a8e44e0bb02e8eb23fd941f62873c60fbbb836/dz4/dz4-2/dz4-2.cpp#L47
Сложная запись какая то
for(int j=0; i < size2 && temp; ++j)
    temp = B[j] == A[i];

https://github.com/SnigurSA/LevelUp_stage1/blob/b2a8e44e0bb02e8eb23fd941f62873c60fbbb836/dz4/dz4-3/dz4-3.cpp#L1
Сдвиги и пробельчики плывут опять

https://github.com/SnigurSA/LevelUp_stage1/blob/b2a8e44e0bb02e8eb23fd941f62873c60fbbb836/dz4/dz4-5/dz4-5.cpp#L17
Длина слова должна быть равна длине строки т.к. строка может быть из одного слова

**Comment by SnigurSA** [comment]
Сложная запись какая то
for(int j=0; i < size2 && temp; ++j)
temp = B[j] == A[i];  в этой строке исправил условие на: temp = B[j] != A[i];

Остальные ошибки исправил
